export const mockCases = [
  {
    id: 'cse_001',
    category: 'fuel',
    name: 'John M.',
    email: 'john.m@example.com',
    status: 'open',
    date: '2025-06-20',
    description: 'Fuel delivery to Gaborone depot was delayed for 3 days without communication.',
  },
  {
    id: 'cse_002',
    category: 'ehs',
    name: 'Lebo P.',
    email: 'lebo.p@example.com',
    status: 'in review',
    date: '2025-06-19',
    description: 'Leak detected in the underground fuel tank at Francistown station.',
  },
  {
    id: 'cse_003',
    category: 'feedback',
    name: 'Tshepo D.',
    email: 'tshepo.d@example.com',
    status: 'closed',
    date: '2025-06-15',
    description: 'Appreciates the new safety signage installed at the depot entrances.',
  },
  {
    id: 'cse_004',
    category: 'fuel',
    name: 'Boitumelo K.',
    email: 'boitumelo.k@example.com',
    status: 'open',
    date: '2025-06-21',
    description: 'Fuel gauge readings are inconsistent after recent maintenance.',
  },
  {
    id: 'cse_005',
    category: 'ehs',
    name: 'Neo R.',
    email: 'neo.r@example.com',
    status: 'in review',
    date: '2025-06-18',
    description: 'Strong chemical smell reported near the ventilation system.',
  },
]
